=== UglyMangoStudios/BaseGame/Server/data/XML/Schemas/RecipeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="RecipeSchema"
    targetNamespace="http://tempuri.org/RecipeSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/RecipeSchema.xsd"
    xmlns:mstns="http://tempuri.org/RecipeSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xi="http://www.w3.org/2001/XInclude"
>
    <xs:complexType name="ResourceDictionary">
        <xs:sequence>

            <xs:element name="Entry" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:attribute name="target" use="required" type="xs:ID">
                    </xs:attribute>
                    <xs:attribute name="qnt" use="required"/>
                </xs:complexType>
                
            </xs:element>

        </xs:sequence>
    </xs:complexType>

   
    <xs:element name="Recipes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Group" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Recipe" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:all maxOccurs="1">
                                        <xs:element name="Output" minOccurs="1"
                                                    type="mstns:ResourceDictionary"/>
                                        <xs:element name="Input" minOccurs="0"
                                                    type="mstns:ResourceDictionary"/>

                                        <xs:element name="Description" minOccurs="0"  type="xs:string"/>
                                    </xs:all>

                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                    <xs:attribute name="time" type="xs:unsignedInt" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                        <xs:attribute name="name" type="xs:string"/>
                    </xs:complexType>
                </xs:element>                
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>

</xs:schema>

=== UglyMangoStudios/BaseGame/Server/data/XML/Recipes.xml
<?xml version="1.0" encoding="utf-8" ?>
<Recipes xmlns="http://tempuri.org/RecipeSchema.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3schools.com file:///C:/Users/kylet/Projects/C%23/SpaceGame/SpaceServer/data/XML/Schemas/RecipeSchema.xsd">


    <Group id="extractions" name="Extractions">
        <Recipe id="harvest_oxygen" name="Harvest Oxygen" time="1">
            <Description>
                A rather simple method of harvesting oxygen from the ground
            </Description>
            <Output>
                <Entry target="oxygen" qnt="1"/>
            </Output>
        </Recipe>
        <Recipe id="mine_iron_ore" name="Mine Iron Ore" time="1">
            <Description>
                A simple method of mining iron from rock.
            </Description>
            <Output>
                <Entry target="iron_ore" qnt="1"/>
            </Output>
        </Recipe>
    </Group>
    

</Recipes>
